feat: staticDistDirを変更

diff --git a/.github/workflows/lighthouse-ci.yml b/.github/workflows/lighthouse-ci.yml
--- a/.github/workflows/lighthouse-ci.yml
+++ b/.github/workflows/lighthouse-ci.yml
@@ -16,7 +16,8 @@ jobs:
 
       - name: Install dependencies
         run: bun install
+
       - name: run Lighthouse CI
         run: |
-          npm install -g @lhci/cli@0.4.x
-          lhci autorun --upload.target=temporary-public-storage --collect.staticDistDir=./src/.vuepress/dist || echo "Lighthouse CI failed!"
+          npm install -g @lhci/cli@0.3.x
+          lhci autorun --upload.target=temporary-public-storage --staticDistDir=./build || echo "LHCI failed!"
